auths:
  public_v2:
    community: public
    version: 2

modules:
  fortigate:
    walk:
      - 1.3.6.1.2.1.2.2.1.8
      - 1.3.6.1.2.1.2.2.1.10
      - 1.3.6.1.2.1.2.2.1.16
      - 1.3.6.1.2.1.31.1.1.1.1
    get:
      - 1.3.6.1.4.1.12356.101.4.1.3.0
      - 1.3.6.1.4.1.12356.101.4.1.4.0
      - 1.3.6.1.4.1.12356.101.4.1.8.0
      - 1.3.6.1.4.1.12356.101.4.1.9.0
    metrics:
      - name: fgSysCpuUsage
        oid: 1.3.6.1.4.1.12356.101.4.1.3
        type: gauge
        help: CPU usage percentage
      - name: fgSysMemUsage
        oid: 1.3.6.1.4.1.12356.101.4.1.4
        type: gauge
        help: Memory usage percentage
      - name: fgSysSesCount
        oid: 1.3.6.1.4.1.12356.101.4.1.8
        type: gauge
        help: Current session count
      - name: fgSysSesRate
        oid: 1.3.6.1.4.1.12356.101.4.1.9
        type: gauge
        help: Session rate per second
      - name: ifName
        oid: 1.3.6.1.2.1.31.1.1.1.1
        type: DisplayString
        help: Interface name
        indexes:
          - labelname: ifIndex
            type: gauge
      - name: ifOperStatus
        oid: 1.3.6.1.2.1.2.2.1.8
        type: gauge
        help: Interface operational status
        indexes:
          - labelname: ifIndex
            type: gauge
        lookups:
          - labels: [ifIndex]
            oid: 1.3.6.1.2.1.31.1.1.1.1
            labelname: ifName
            type: DisplayString
      - name: ifInOctets_total
        oid: 1.3.6.1.2.1.2.2.1.10
        type: counter
        help: Interface bytes received
        indexes:
          - labelname: ifIndex
            type: gauge
        lookups:
          - labels: [ifIndex]
            oid: 1.3.6.1.2.1.31.1.1.1.1
            labelname: ifName
            type: DisplayString
      - name: ifOutOctets_total
        oid: 1.3.6.1.2.1.2.2.1.16
        type: counter
        help: Interface bytes transmitted
        indexes:
          - labelname: ifIndex
            type: gauge
        lookups:
          - labels: [ifIndex]
            oid: 1.3.6.1.2.1.31.1.1.1.1
            labelname: ifName
            type: DisplayString
